framework:
  rate_limiter:
    message_send:
      policy: 'fixed_window'
      limit: '%env(int:NOTIFICATION_SEND_LIMIT)%'
      interval: '%env(NOTIFICATION_SEND_LIMIT_INTERVAL)%'
      cache_pool: 'cache.app'