parameters:
    notification.channels_config:
        email: '%env(bool:MAIL_CHANNEL_ENABLED)%'
        sms: '%env(bool:SMS_CHANNEL_ENABLED)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\CQRS\CommandHandlerInterface:
            tags: { name: messenger.message_handler, bus: command.bus }

        App\NotificationPublisher\Domain\Service\Notification\Channel\ChannelInterface:
            tags: [ 'app.notification_channel' ]

        App\NotificationPublisher\Domain\Sender\MailerInterface:
            tags: [ 'app.mailer_sender' ]

    App\NotificationPublisher\Domain\Service\Notification\Notifier:
        arguments:
            - !tagged_iterator 'app.notification_channel'
            - '%notification.channels_config%'
            - '%env(int:NOTIFICATION_SEND_LIMIT)%'

    App\NotificationPublisher\Domain\Service\Notification\Channel\EmailChannel:
        arguments:
            - !tagged_iterator 'app.mailer_sender'

    App\NotificationPublisher\Domain\Service\Notification\Channel\SMSChannel: ~

    App\NotificationPublisher\UserInterface\Console\SendNotificationsCommand: ~

    App\NotificationPublisher\Application\CQRS\Command\SendNotificationHandler: ~

    App\NotificationPublisher\Infrastructure\Sender\Email\MailTrap:
        tags:
          - { name: 'app.mailer_sender', priority: 20 }
        arguments:
            $apiKey: '%env(MAIL_TRAP_API_KEY)%'
            $fromEmail: '%env(MAIL_FROM_EMAIL)%'
            $fromName: '%env(MAIL_FROM_NAME)%'

    App\NotificationPublisher\Infrastructure\Sender\Email\MailerSend:
        tags:
            - { name: 'app.mailer_sender', priority: 10 }
        arguments:
            $apiKey: '%env(MAILER_SEND_API_KEY)%'
            $fromEmail: '%env(MAIL_FROM_EMAIL)%'
            $fromName: '%env(MAIL_FROM_NAME)%'

    App\NotificationPublisher\Infrastructure\Sender\SMS\SMS:
        arguments:
            $sid: '%env(SMS_TWILIO_SID)%'
            $authToken: '%env(SMS_TWILIO_AUTH_TOKEN)%'
            $fromNumber: '%env(SMS_TWILIO_FROM_NUMBER)%'

    App\NotificationPublisher\Domain\Sender\SMSInterface: '@App\NotificationPublisher\Infrastructure\Sender\SMS\SMS'

    App\NotificationPublisher\Domain\Factory\NotificationDTOFactory: ~

    App\NotificationPublisher\Infrastructure\Limiter\MessageSendLimiter: ~

    App\NotificationPublisher\Domain\Limiter\MessageSendLimiterInterface: '@App\NotificationPublisher\Infrastructure\Limiter\MessageSendLimiter'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
