parameters:
    notification.channels_config:
        email: '%env(bool:MAIL_CHANNEL_ENABLED)%'
        sms: '%env(bool:SMS_CHANNEL_ENABLED)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\CQRS\CommandHandlerInterface:
            tags: { name: messenger.message_handler, bus: command.bus }

    App\NotificationPublisher\Domain\Service\Notification\Notifier:
        arguments:
            $notificationSendLimit: '%env(int:NOTIFICATION_SEND_LIMIT)%'

    App\NotificationPublisher\UserInterface\Console\SendNotificationsCommand: ~

    App\NotificationPublisher\Application\CQRS\Command\SendNotificationHandler: ~

    App\NotificationPublisher\Domain\Factory\NotificationDTOFactory:
        arguments:
            - '%notification.channels_config%'

    App\NotificationPublisher\Infrastructure\Limiter\MessageSendLimiter: ~

    App\NotificationPublisher\Domain\Limiter\MessageSendLimiterInterface: '@App\NotificationPublisher\Infrastructure\Limiter\MessageSendLimiter'

    App\NotificationPublisher\Infrastructure\Notifier\Notifier: ~

    App\NotificationPublisher\Domain\Notifier\NotifierInterface: '@App\NotificationPublisher\Infrastructure\Notifier\Notifier'

    App\NotificationPublisher\NotificationPublisherFacade: ~

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\NotificationPublisher\NotificationPublisherFacade:
            public: true
