imports:
    - { resource: '../src/NotificationPublisher/Infrastructure/Resources/config/services.yaml'}
    - { resource: '../src/Shared/Infrastructure/Resources/config/services.yaml'}

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

