framework:
    notifier:
        chatter_transports:
            mailer: '%env(MAILER_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'sms']
            high: ['email', 'sms']
            medium: ['email', 'sms']
            low: ['email', 'sms']
        admin_recipients:
            - { email: admin@example.com }